name: Publish VSCode Extension

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: VScode_extension
        run: npm ci

      - name: Package VSIX
        working-directory: VScode_extension
        run: npm run package

      - name: Publish to Visual Studio Marketplace
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
        working-directory: VScode_extension
        run: npx vsce publish -p "$VSCE_TOKEN"

      - name: Publish to Open VSX (optional)
        if: env.OVSX_TOKEN != ''
        env:
          OVSX_TOKEN: ${{ secrets.OVSX_TOKEN }}
        working-directory: VScode_extension
        run: npx ovsx publish -p "$OVSX_TOKEN" VScode_extension/voice-commander-*.vsix

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v3
        with:
          name: voice-commander-vsix
          path: VScode_extension/*.vsix 